# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
title: Ariadna Ballestar Fotografía · Sesiones de fotografía en Barcelona

description: > # this means to ignore newlines until "baseurl:"
  Encuentra las mejores sesiones de fotografía realizadas en Barcelona por la fotografa profesional, de Fraga, Ariadna Ballestar.
url: "https://ariadnaballestar.com" # the base hostname & protocol for your site
facebook:
  publisher: https://www.facebook.com/ari.ballestar
author: "Ariadna Ballestar"
logo: https://ariadnaballestar.com/assets/logos/logo-negro.png
social: 
  name: Ariadna Ballestar Fotografía
  links:
    - https://www.instagram.com/ariadna_ballestar/
    - https://www.facebook.com/ari.ballestar

baseurl: "/sesiones" # the subpath of your site, e.g. /blog

email: info@ariadnaballestar.com
# Build settings
markdown: kramdown
